import type {
  Conversation,
  EmotionDefinition,
  EmotionKey,
  EmotionMoment,
  EmotionNote,
  FollowUpRecord,
} from './types';

export const EMOTIONS: Record<EmotionKey, EmotionDefinition> = {
  calm: {
    key: 'calm',
    label: '平静',
    shortLabel: '静',
    color: '#7F9E91',
    softColor: '#DCE8E1',
    description: '安稳、松弛，暂时不需要应对什么',
    score: 2,
  },
  joy: {
    key: 'joy',
    label: '开心',
    shortLabel: '喜',
    color: '#D9B94F',
    softColor: '#F6E9A9',
    description: '轻快、明亮，愿意靠近此刻',
    score: 3,
  },
  tender: {
    key: 'tender',
    label: '柔软',
    shortLabel: '柔',
    color: '#D2936D',
    softColor: '#F1D6C6',
    description: '被理解、被触动，心里有一点温度',
    score: 2,
  },
  curious: {
    key: 'curious',
    label: '好奇',
    shortLabel: '奇',
    color: '#CBE0E8',
    softColor: '#E8F2F5',
    description: '想靠近看看，注意力正在轻轻打开',
    score: 1,
  },
  energized: {
    key: 'energized',
    label: '有活力',
    shortLabel: '力',
    color: '#C4D4C5',
    softColor: '#E6EEE7',
    description: '身体有动力，想开始做一点什么',
    score: 2,
  },
  connected: {
    key: 'connected',
    label: '亲近',
    shortLabel: '近',
    color: '#D0D5C1',
    softColor: '#ECEEE5',
    description: '和人、地点或此刻有连接感',
    score: 2,
  },
  heavy: {
    key: 'heavy',
    label: '低落',
    shortLabel: '低',
    color: '#777F8F',
    softColor: '#D8DAE2',
    description: '沉重、迟缓，想减少外界输入',
    score: -2,
  },
  restless: {
    key: 'restless',
    label: '不安',
    shortLabel: '躁',
    color: '#A48CAA',
    softColor: '#E7DDE8',
    description: '警觉、悬着，注意力很难落下来',
    score: -1,
  },
  focused: {
    key: 'focused',
    label: '专注',
    shortLabel: '专',
    color: '#7297AE',
    softColor: '#D8E7ED',
    description: '清晰、投入，世界暂时变得简单',
    score: 1,
  },
  overwhelmed: {
    key: 'overwhelmed',
    label: '过载',
    shortLabel: '载',
    color: '#A96F70',
    softColor: '#EBD7D6',
    description: '声音、信息或感受一下子太多',
    score: -3,
  },
  numb: {
    key: 'numb',
    label: '麻木',
    shortLabel: '木',
    color: '#F0EBE1',
    softColor: '#F8F5EF',
    description: '感觉很远、很淡，暂时不想处理更多',
    score: -2,
  },
  mixed: {
    key: 'mixed',
    label: '混合',
    shortLabel: '杂',
    color: '#28292B',
    softColor: '#D8D8D9',
    description: '几种感受同时出现，还不需要分清楚',
    score: 0,
  },
};

export const EMOTION_ORDER: EmotionKey[] = [
  'calm',
  'joy',
  'tender',
  'curious',
  'energized',
  'connected',
  'focused',
  'restless',
  'heavy',
  'overwhelmed',
  'numb',
  'mixed',
];

export const GUIDED_NOTE_QUESTIONS = [
  '你去这里做什么？',
  '当时感觉如何？',
  '还有什么想记录的吗？',
] as const;

export const INITIAL_MOMENTS: EmotionMoment[] = [
  {
    id: 'library-noise',
    emotion: 'focused',
    intensity: 4,
    place: '东国大学中央图书馆',
    date: '2026-07-28',
    time: '10:20',
    longitude: 126.9994,
    latitude: 37.5582,
    noteId: 'note-library',
    placeRating: 'safe',
    tagGroupId: 1001,
    tagOrder: 1,
  },
  {
    id: 'cafeteria-pause',
    emotion: 'connected',
    intensity: 4,
    place: '万海广场',
    date: '2026-07-29',
    time: '12:35',
    longitude: 127.0003,
    latitude: 37.5579,
    noteId: 'note-cafeteria',
    placeRating: 'comfortable',
    tagGroupId: 1001,
    tagOrder: 2,
  },
  {
    id: 'studio-focus',
    emotion: 'overwhelmed',
    intensity: 4,
    place: '惠化馆走廊',
    date: '2026-07-30',
    time: '15:10',
    longitude: 127.0008,
    latitude: 37.5591,
    noteId: 'note-studio',
    placeRating: 'uneasy',
    tagGroupId: 1001,
    tagOrder: 3,
  },
  {
    id: 'river-calm',
    emotion: 'tender',
    intensity: 3,
    place: '常绿园学生食堂',
    date: '2026-07-31',
    time: '18:05',
    longitude: 127.0012,
    latitude: 37.5587,
    noteId: 'note-river',
    placeRating: 'comfortable',
  },
  {
    id: 'evening-crowd',
    emotion: 'calm',
    intensity: 4,
    place: '八正道',
    date: '2026-08-01',
    time: '09:15',
    longitude: 126.9988,
    latitude: 37.5577,
    noteId: 'note-crossing',
    placeRating: 'safe',
  },
];

export const INITIAL_NOTES: EmotionNote[] = [
  {
    id: 'note-library',
    title: '图书馆靠窗复习',
    place: '东国大学中央图书馆',
    date: '2026-07-28',
    time: '10:20',
    emotion: 'focused',
    placeRating: 'safe',
    excerpt: '上午的靠窗座位比较安静，我把下午课程的阅读材料整理完了。',
    answers: [
      {
        id: 'why',
        question: GUIDED_NOTE_QUESTIONS[0],
        answer: '复习下午课程的阅读材料。',
      },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '靠窗的位置光线稳定，周围只有翻书声。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '上午十点前来更容易找到这个位置。',
      },
    ],
  },
  {
    id: 'note-cafeteria',
    title: '万海广场上的午饭',
    place: '万海广场',
    date: '2026-07-29',
    time: '12:35',
    emotion: 'connected',
    placeRating: 'comfortable',
    excerpt: '小组讨论结束后，和同学带着午饭坐在广场边聊了一会儿。',
    answers: [
      {
        id: 'why',
        question: GUIDED_NOTE_QUESTIONS[0],
        answer: '和小组同学一起吃午饭。',
      },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '大家聊了课堂之外的事，我没有急着赶下一件任务。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '广场边有阴影，午休时间也能坐得下。',
      },
    ],
  },
  {
    id: 'note-studio',
    title: '下课时的惠化馆走廊',
    place: '惠化馆走廊',
    date: '2026-07-30',
    time: '15:10',
    emotion: 'overwhelmed',
    placeRating: 'uneasy',
    excerpt: '两节课同时结束，走廊里的脚步声和谈话声一下子叠在一起。',
    answers: [
      { id: 'why', question: GUIDED_NOTE_QUESTIONS[0], answer: '下课后去下一间教室。' },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '人流集中在楼梯口，我需要停一下再判断方向。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '错开五分钟离开可能会更轻松。',
      },
    ],
  },
  {
    id: 'note-river',
    title: '常绿园食堂的晚饭',
    place: '常绿园学生食堂',
    date: '2026-07-31',
    time: '18:05',
    emotion: 'tender',
    placeRating: 'comfortable',
    excerpt: '社团活动结束得晚，同学帮我留了一份晚饭，我们慢慢吃完才离开。',
    answers: [
      {
        id: 'why',
        question: GUIDED_NOTE_QUESTIONS[0],
        answer: '社团活动结束后吃晚饭。',
      },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '不用一边吃一边赶时间，坐下来以后轻松了一些。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '下次活动晚结束也可以先来这里看看。',
      },
    ],
  },
  {
    id: 'note-crossing',
    title: '早课前经过八正道',
    place: '八正道',
    date: '2026-08-01',
    time: '09:15',
    emotion: 'calm',
    placeRating: 'safe',
    excerpt: '雨刚停，去教室的路上人还不多，石板路边的树叶很亮。',
    answers: [
      {
        id: 'why',
        question: GUIDED_NOTE_QUESTIONS[0],
        answer: '去明真馆上早课。',
      },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '雨后的路比较安静，走路的节奏也慢了下来。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '早点出门时，这段路不会太拥挤。',
      },
    ],
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpRecord[] = [
  {
    id: 'follow-up-library-3d',
    noteId: 'note-cafeteria',
    intervalDays: 3,
    dueAt: '2026-08-01T12:35:00+09:00',
    status: 'active',
    prompt:
      '三天前，你记录了在万海广场和同学一起吃午饭。现在回看，这段经历里有什么正面的部分仍然值得留下？',
    promptedAt: '2026-08-01T12:35:00+09:00',
  },
  {
    id: 'follow-up-studio-3d',
    noteId: 'note-library',
    intervalDays: 3,
    dueAt: '2026-08-02T10:20:00+09:00',
    status: 'queued',
    prompt:
      '你在中央图书馆靠窗的位置留下了一颗“专注”的星星。现在回看，那次学习经历还有哪些部分值得保留？',
  },
  {
    id: 'follow-up-river-3d',
    noteId: 'note-crossing',
    intervalDays: 3,
    dueAt: '2026-08-04T09:15:00+09:00',
    status: 'queued',
    prompt:
      '你在雨后的八正道记录了“平静”。现在回看，那段上课前的路给你的感觉有变化吗？',
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'thread-patterns',
    title: '校园里哪些地方更适合学习？',
    preview: '两条记录都提到了环境里的声音和人流。',
    kind: 'regular',
    messages: [
      {
        id: 'm1',
        role: 'user',
        body: '我想比较图书馆和惠化馆走廊这两次记录。',
        noteIds: ['note-library', 'note-studio'],
      },
      {
        id: 'm2',
        role: 'assistant',
        body: '图书馆记录里，你写到靠窗位置只有翻书声；惠化馆记录里，两节课同时结束，脚步声、谈话声和人流集中出现。现有记录支持的差别是当时环境输入的数量不同。',
      },
      {
        id: 'm3',
        role: 'user',
        body: '对，我在走廊里需要先停一下再判断往哪里走。',
      },
      {
        id: 'm4',
        role: 'assistant',
        body: '这与惠化馆记录里的原话一致。图书馆只有一条记录，现有数据还不足以概括所有适合学习的地方。',
      },
    ],
  },
  {
    id: 'thread-revisit',
    title: '交流回访',
    preview: '想看看现在如何理解这条记录吗？',
    unread: true,
    kind: 'companion',
    messages: [
      {
        id: 'r1',
        role: 'assistant',
        body: INITIAL_FOLLOW_UPS[0].prompt ?? '现在回看，这段经历有什么变化？',
        noteIds: ['note-cafeteria'],
        followUpId: INITIAL_FOLLOW_UPS[0].id,
        createdAt: INITIAL_FOLLOW_UPS[0].promptedAt,
        options: [
          {
            id: 'better',
            label: '现在回看，感受轻了一些。',
            responseKind: 'lighter',
          },
          {
            id: 'more-intense',
            label: '现在回看，感受更强烈了。',
            responseKind: 'stronger',
          },
          {
            id: 'different',
            label: '感受有变化，但我还说不清。',
            responseKind: 'different',
          },
          {
            id: 'same',
            label: '和当时差不多。',
            responseKind: 'same',
          },
          {
            id: 'skip',
            label: '我暂时不想回看。',
            responseKind: 'skip',
          },
        ],
      },
    ],
  },
  {
    id: 'thread-place',
    title: '最近校园里有哪些舒服的时刻？',
    preview: '万海广场、常绿园和八正道各有一条正面记录。',
    kind: 'regular',
    messages: [
      {
        id: 'p1',
        role: 'user',
        body: '最近在学校有哪些感觉比较舒服的记录？',
        noteIds: ['note-cafeteria', 'note-river', 'note-crossing'],
      },
      {
        id: 'p2',
        role: 'assistant',
        body: '目前有三条：万海广场午饭记录为“亲近”，常绿园晚饭记录为“柔软”，八正道早课前记录为“平静”。它们发生在不同日期和地点，现有记录不足以判断是否形成长期规律。',
      },
    ],
  },
];
