import type { EmotionDefinition, EmotionKey } from './types';

export const EMOTIONS: Record<EmotionKey, EmotionDefinition> = {
  calm: {
    key: 'calm',
    label: '平静',
    shortLabel: '静',
    color: '#7F9E91',
    softColor: '#DCE8E1',
    description: '安稳、松弛，暂时不需要应对什么',
    score: 2,
  },
  joy: {
    key: 'joy',
    label: '开心',
    shortLabel: '喜',
    color: '#D9B94F',
    softColor: '#F6E9A9',
    description: '轻快、明亮，愿意靠近此刻',
    score: 3,
  },
  tender: {
    key: 'tender',
    label: '柔软',
    shortLabel: '柔',
    color: '#D2936D',
    softColor: '#F1D6C6',
    description: '被理解、被触动，心里有一点温度',
    score: 2,
  },
  curious: {
    key: 'curious',
    label: '好奇',
    shortLabel: '奇',
    color: '#CBE0E8',
    softColor: '#E8F2F5',
    description: '想靠近看看，注意力正在轻轻打开',
    score: 1,
  },
  energized: {
    key: 'energized',
    label: '有活力',
    shortLabel: '力',
    color: '#C4D4C5',
    softColor: '#E6EEE7',
    description: '身体有动力，想开始做一点什么',
    score: 2,
  },
  connected: {
    key: 'connected',
    label: '亲近',
    shortLabel: '近',
    color: '#D0D5C1',
    softColor: '#ECEEE5',
    description: '和人、地点或此刻有连接感',
    score: 2,
  },
  heavy: {
    key: 'heavy',
    label: '低落',
    shortLabel: '低',
    color: '#777F8F',
    softColor: '#D8DAE2',
    description: '沉重、迟缓，想减少外界输入',
    score: -2,
  },
  restless: {
    key: 'restless',
    label: '不安',
    shortLabel: '躁',
    color: '#A48CAA',
    softColor: '#E7DDE8',
    description: '警觉、悬着，注意力很难落下来',
    score: -1,
  },
  focused: {
    key: 'focused',
    label: '专注',
    shortLabel: '专',
    color: '#7297AE',
    softColor: '#D8E7ED',
    description: '清晰、投入，世界暂时变得简单',
    score: 1,
  },
  overwhelmed: {
    key: 'overwhelmed',
    label: '过载',
    shortLabel: '载',
    color: '#A96F70',
    softColor: '#EBD7D6',
    description: '声音、信息或感受一下子太多',
    score: -3,
  },
  numb: {
    key: 'numb',
    label: '麻木',
    shortLabel: '木',
    color: '#F0EBE1',
    softColor: '#F8F5EF',
    description: '感觉很远、很淡，暂时不想处理更多',
    score: -2,
  },
  mixed: {
    key: 'mixed',
    label: '混合',
    shortLabel: '杂',
    color: '#28292B',
    softColor: '#D8D8D9',
    description: '几种感受同时出现，还不需要分清楚',
    score: 0,
  },
};

export const EMOTION_ORDER: EmotionKey[] = [
  'calm',
  'joy',
  'tender',
  'curious',
  'energized',
  'connected',
  'focused',
  'restless',
  'heavy',
  'overwhelmed',
  'numb',
  'mixed',
];
