import type {
  Conversation,
  EmotionDefinition,
  EmotionKey,
  EmotionMoment,
  EmotionNote,
  FollowUpRecord,
} from './types';

export const EMOTIONS: Record<EmotionKey, EmotionDefinition> = {
  calm: {
    key: 'calm',
    label: '平静',
    shortLabel: '静',
    color: '#7F9E91',
    softColor: '#DCE8E1',
    description: '安稳、松弛，暂时不需要应对什么',
    score: 2,
  },
  joy: {
    key: 'joy',
    label: '开心',
    shortLabel: '喜',
    color: '#D9B94F',
    softColor: '#F6E9A9',
    description: '轻快、明亮，愿意靠近此刻',
    score: 3,
  },
  tender: {
    key: 'tender',
    label: '柔软',
    shortLabel: '柔',
    color: '#D2936D',
    softColor: '#F1D6C6',
    description: '被理解、被触动，心里有一点温度',
    score: 2,
  },
  curious: {
    key: 'curious',
    label: '好奇',
    shortLabel: '奇',
    color: '#CBE0E8',
    softColor: '#E8F2F5',
    description: '想靠近看看，注意力正在轻轻打开',
    score: 1,
  },
  energized: {
    key: 'energized',
    label: '有活力',
    shortLabel: '力',
    color: '#C4D4C5',
    softColor: '#E6EEE7',
    description: '身体有动力，想开始做一点什么',
    score: 2,
  },
  connected: {
    key: 'connected',
    label: '亲近',
    shortLabel: '近',
    color: '#D0D5C1',
    softColor: '#ECEEE5',
    description: '和人、地点或此刻有连接感',
    score: 2,
  },
  heavy: {
    key: 'heavy',
    label: '低落',
    shortLabel: '低',
    color: '#777F8F',
    softColor: '#D8DAE2',
    description: '沉重、迟缓，想减少外界输入',
    score: -2,
  },
  restless: {
    key: 'restless',
    label: '不安',
    shortLabel: '躁',
    color: '#A48CAA',
    softColor: '#E7DDE8',
    description: '警觉、悬着，注意力很难落下来',
    score: -1,
  },
  focused: {
    key: 'focused',
    label: '专注',
    shortLabel: '专',
    color: '#7297AE',
    softColor: '#D8E7ED',
    description: '清晰、投入，世界暂时变得简单',
    score: 1,
  },
  overwhelmed: {
    key: 'overwhelmed',
    label: '过载',
    shortLabel: '载',
    color: '#A96F70',
    softColor: '#EBD7D6',
    description: '声音、信息或感受一下子太多',
    score: -3,
  },
  numb: {
    key: 'numb',
    label: '麻木',
    shortLabel: '木',
    color: '#F0EBE1',
    softColor: '#F8F5EF',
    description: '感觉很远、很淡，暂时不想处理更多',
    score: -2,
  },
  mixed: {
    key: 'mixed',
    label: '混合',
    shortLabel: '杂',
    color: '#28292B',
    softColor: '#D8D8D9',
    description: '几种感受同时出现，还不需要分清楚',
    score: 0,
  },
};

export const EMOTION_ORDER: EmotionKey[] = [
  'calm',
  'joy',
  'tender',
  'curious',
  'energized',
  'connected',
  'focused',
  'restless',
  'heavy',
  'overwhelmed',
  'numb',
  'mixed',
];

export const GUIDED_NOTE_QUESTIONS = [
  '你去这里做什么？',
  '当时感觉如何？',
  '还有什么想记录的吗？',
] as const;

export const INITIAL_MOMENTS: EmotionMoment[] = [
  {
    id: 'library-noise',
    emotion: 'overwhelmed',
    intensity: 5,
    place: '中央图书馆',
    date: '2026-07-22',
    time: '14:10',
    longitude: 126.9527,
    latitude: 37.5578,
    noteId: 'note-library',
    placeRating: 'distressing',
    tagGroupId: 1001,
    tagOrder: 1,
  },
  {
    id: 'cafeteria-pause',
    emotion: 'tender',
    intensity: 3,
    place: '学生食堂外',
    date: '2026-07-22',
    time: '16:35',
    longitude: 126.9553,
    latitude: 37.5562,
    noteId: 'note-cafeteria',
    placeRating: 'comfortable',
    tagGroupId: 1001,
    tagOrder: 2,
  },
  {
    id: 'studio-focus',
    emotion: 'focused',
    intensity: 4,
    place: '设计工作室',
    date: '2026-07-23',
    time: '11:42',
    longitude: 126.9581,
    latitude: 37.5547,
    noteId: 'note-studio',
    placeRating: 'safe',
    tagGroupId: 1001,
    tagOrder: 3,
  },
  {
    id: 'river-calm',
    emotion: 'calm',
    intensity: 4,
    place: '河边步道',
    date: '2026-07-24',
    time: '15:08',
    longitude: 126.9494,
    latitude: 37.5541,
    noteId: 'note-river',
    placeRating: 'safe',
  },
  {
    id: 'evening-crowd',
    emotion: 'restless',
    intensity: 3,
    place: '南门十字路口',
    date: '2026-07-24',
    time: '19:27',
    longitude: 126.9569,
    latitude: 37.5529,
    noteId: 'note-crossing',
    placeRating: 'uneasy',
  },
];

export const INITIAL_NOTES: EmotionNote[] = [
  {
    id: 'note-library',
    title: '图书馆里声音一下子太多',
    place: '中央图书馆',
    date: '2026-07-22',
    time: '14:10',
    emotion: 'overwhelmed',
    placeRating: 'distressing',
    excerpt: '空调、翻书声和旁边的谈话叠在一起，我很难继续看下去。',
    answers: [
      {
        id: 'why',
        question: GUIDED_NOTE_QUESTIONS[0],
        answer: '本来想安静地完成一份作业。',
      },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '声音和谈话叠在一起，肩膀很紧，想马上离开。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '座位比平时拥挤。',
      },
    ],
  },
  {
    id: 'note-cafeteria',
    title: '有人给我留了一个安静的位置',
    place: '学生食堂外',
    date: '2026-07-22',
    time: '16:35',
    emotion: 'tender',
    placeRating: 'comfortable',
    excerpt: '没有被追问发生了什么，只是一起坐了一会儿。',
    answers: [
      {
        id: 'why',
        question: GUIDED_NOTE_QUESTIONS[0],
        answer: '从图书馆出来以后想找个地方坐一会儿。',
      },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '坐了一会儿后，呼吸比刚离开图书馆时慢了一些。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '有人在旁边陪我坐了一会儿，没有追问。',
      },
    ],
  },
  {
    id: 'note-studio',
    title: '工作室终于安静下来',
    place: '设计工作室',
    date: '2026-07-23',
    time: '11:42',
    emotion: 'focused',
    placeRating: 'safe',
    excerpt: '把桌面收干净以后，我终于能只看眼前这一件事。',
    answers: [
      { id: 'why', question: GUIDED_NOTE_QUESTIONS[0], answer: '整理界面草图。' },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '呼吸慢下来，注意力回到眼前的工作。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '工作室里人很少，桌面已经收干净。',
      },
    ],
  },
  {
    id: 'note-river',
    title: '在河边走了更远的一段',
    place: '河边步道',
    date: '2026-07-24',
    time: '15:08',
    emotion: 'calm',
    placeRating: 'safe',
    excerpt: '今天不需要马上想清楚什么，只是继续往前走。',
    answers: [
      {
        id: 'why',
        question: GUIDED_NOTE_QUESTIONS[0],
        answer: '散步，没有特别的目的。',
      },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '步伐和呼吸都比较平稳。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '路上人不多，风吹过树叶。',
      },
    ],
  },
  {
    id: 'note-crossing',
    title: '回家路上的人群',
    place: '南门十字路口',
    date: '2026-07-24',
    time: '19:27',
    emotion: 'restless',
    placeRating: 'uneasy',
    excerpt: '路口很亮，人流一直从旁边擦过去。',
    answers: [
      {
        id: 'why',
        question: GUIDED_NOTE_QUESTIONS[0],
        answer: '从学校回家，经过南门十字路口。',
      },
      {
        id: 'around',
        question: GUIDED_NOTE_QUESTIONS[1],
        answer: '肩颈发紧，注意力一直被人流和方向拉走。',
      },
      {
        id: 'body',
        question: GUIDED_NOTE_QUESTIONS[2],
        answer: '下班和放学的人挤在同一个路口。',
      },
    ],
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpRecord[] = [
  {
    id: 'follow-up-library-3d',
    noteId: 'note-library',
    intervalDays: 3,
    dueAt: '2026-07-25T14:10:00+08:00',
    status: 'active',
    prompt:
      '三天前，你把中央图书馆标记成了“很难受”。现在回看，这段经历给你的感觉有变化吗？如果你愿意，我也可以在之后继续回访。',
    promptedAt: '2026-07-25T14:10:00+08:00',
  },
  {
    id: 'follow-up-studio-3d',
    noteId: 'note-studio',
    intervalDays: 3,
    dueAt: '2026-07-26T11:42:00+08:00',
    status: 'queued',
    prompt:
      '三天前，你在设计工作室留下了一颗星星，当时记录为“专注”。现在回看，那次经历给你的感觉有变化吗？',
  },
  {
    id: 'follow-up-river-3d',
    noteId: 'note-river',
    intervalDays: 3,
    dueAt: '2026-07-27T15:08:00+08:00',
    status: 'queued',
    prompt:
      '三天前，你在河边步道留下了一颗星星，当时记录为“平静”。现在回看，那次经历给你的感觉有变化吗？',
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'thread-patterns',
    title: '声音很多的时候，我会怎样？',
    preview: '也许真正消耗你的不是声音本身……',
    kind: 'regular',
    messages: [
      {
        id: 'm1',
        role: 'user',
        body: '我想一起看看这两次记录有没有关系。',
        noteIds: ['note-library', 'note-crossing'],
      },
      {
        id: 'm2',
        role: 'assistant',
        body: '我读完了。两次都出现了很多同时发生、需要你快速筛选的信息：图书馆是声音，路口是人流和方向。你描述的不是“讨厌热闹”，更像是输入同时涌进来以后，很难决定先处理哪一个。',
      },
      {
        id: 'm3',
        role: 'user',
        body: '对，我最难受的是没办法把其中一个声音关掉。',
      },
      {
        id: 'm4',
        role: 'assistant',
        body: '那我们可以先把它写成一句更贴近你的话：“当很多输入同时出现时，我需要减少选择，而不是被催着适应。”你想保留这句话，还是换成更日常的表达？',
      },
    ],
  },
  {
    id: 'thread-revisit',
    title: '交流回访',
    preview: '想看看现在如何理解这条记录吗？',
    unread: true,
    kind: 'companion',
    messages: [
      {
        id: 'r1',
        role: 'assistant',
        body: INITIAL_FOLLOW_UPS[0].prompt,
        noteIds: ['note-library'],
        followUpId: INITIAL_FOLLOW_UPS[0].id,
        createdAt: INITIAL_FOLLOW_UPS[0].promptedAt,
        options: [
          {
            id: 'better',
            label: '现在回看，感受轻了一些。',
            responseKind: 'calm',
          },
          {
            id: 'more-intense',
            label: '现在回看，感受更强烈了。',
            responseKind: 'stronger',
          },
          {
            id: 'different',
            label: '感受有变化，但我还说不清。',
            responseKind: 'different',
          },
          {
            id: 'same',
            label: '和当时差不多。',
            responseKind: 'unchanged',
          },
          {
            id: 'skip',
            label: '我暂时不想回看。',
            responseKind: 'skip',
          },
        ],
      },
    ],
  },
  {
    id: 'thread-place',
    title: '什么样的地方让我容易专注？',
    preview: '工作室和河边有一个共同点……',
    kind: 'regular',
    messages: [
      {
        id: 'p1',
        role: 'user',
        body: '为什么有些地方我会比较容易静下来？',
        noteIds: ['note-studio', 'note-river'],
      },
      {
        id: 'p2',
        role: 'assistant',
        body: '这两条记录里，你都不需要同时回应很多人，也可以自己决定节奏。一个是视觉上变简单，一个是没有明确任务。它们可能都给了你“可以只处理一件事”的空间。',
      },
    ],
  },
];
